###*
# Admin
###

Security.defineMethod 'restuarant_ifAdmin',
  fetch: []
  transform: null
  deny: (type, arg, userId) ->
    !Roles.userIsInRole(userId, [ 'admin' ], 'Restuarant')

###*
# General
###

Security.defineMethod 'restuarant_ifGeneral',
  fetch: []
  transform: null
  deny: (type, arg, userId) ->
    !Roles.userIsInRole(userId, [ 'general' ], 'Restuarant')

###*
# Reporter
###

Security.defineMethod 'restuarant_ifReporter',
  fetch: []
  transform: null
  deny: (type, arg, userId) ->
    !Roles.userIsInRole(userId, [ 'reporter' ], 'Restuarant')

# ---
# generated by js2coffee 2.0.4
